# Generated by Django 3.0.6 on 2020-05-30 14:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.TextField(max_length=20)),
                ('nombre', models.TextField(max_length=50)),
                ('descripcion', models.TextField(max_length=500)),
                ('direccion', models.TextField(max_length=200)),
                ('localizacion', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TiendaHorario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.BooleanField()),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tienda')),
            ],
        ),
    ]
