# Generated by Django 3.0.6 on 2020-05-30 17:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='codigo_interno',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='localizacion',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
