# Generated by Django 3.0.6 on 2020-05-31 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200530_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiendahorario',
            name='dia_especifico',
            field=models.DateField(blank=True, default=None, verbose_name='Día específico'),
        ),
        migrations.AlterField(
            model_name='tiendahorario',
            name='dia_semana',
            field=models.IntegerField(choices=[(0, 'Lun'), (1, 'Mar'), (2, 'Mie'), (3, 'Jue'), (4, 'Vie'), (5, 'Sab'), (6, 'Dom')], verbose_name='Día de la semana'),
        ),
        migrations.AlterField(
            model_name='tiendahorario',
            name='estado',
            field=models.BooleanField(verbose_name='Habilitado'),
        ),
        migrations.AlterField(
            model_name='tiendahorario',
            name='hora_fin',
            field=models.TimeField(verbose_name='Hora de fin'),
        ),
        migrations.AlterField(
            model_name='tiendahorario',
            name='hora_inicio',
            field=models.TimeField(verbose_name='Hora de inicio'),
        ),
    ]
