# Generated by Django 3.0.6 on 2020-06-01 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200531_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiendahorario',
            name='estado',
        ),
        migrations.AddField(
            model_name='tiendahorario',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='tiendahorario',
            name='dia_semana',
            field=models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miercoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sabado'), (6, 'Domingo')], verbose_name='Día de la semana'),
        ),
        migrations.CreateModel(
            name='TiendaCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre de categoría')),
                ('activa', models.BooleanField()),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tienda')),
            ],
        ),
    ]
