# Generated by Django 3.0.6 on 2020-06-05 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200601_0606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tienda',
            options={'verbose_name': 'Tienda'},
        ),
        migrations.AlterModelOptions(
            name='tiendacategoria',
            options={'verbose_name': 'Categoría'},
        ),
        migrations.AlterModelOptions(
            name='tiendahorario',
            options={'verbose_name': 'Horario'},
        ),
        migrations.AddField(
            model_name='tiendacategoria',
            name='categoriaPadre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.TiendaCategoria'),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='estado',
            field=models.BooleanField(verbose_name='Activo'),
        ),
    ]
